# Generated by Django 4.2.8 on 2024-08-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unconfirmed_new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
